* What

This repository provides a self-contained bench-marking load-test
script for Hasura.  It addresses the following question.

#+begin_quote
What is an estimate on the through-put of Hasura under load, under
ideal circumstances?
#+end_quote

*** Definitions

- through-put :: the number or requests-per-second (RPS) without
  errors sustainable by Hasura
- under load :: the load driver k6 is run as a load test and with a
  sufficiently high number of virtual users to saturate Hasura
- saturate :: A server is saturated when the rate of responses it
  provides without error no longer increases as the rate of requests
  increases.
- ideal circumstances :: The test issues GraphQL queries only, without
  mutations or subscriptions.  The metadata is never reloaded.  The
  database (both for data and for metadata) is on a different host
  from Hasura.  Moreover, the database is provisioned on
  vertically-scaled infrastructure with capacity well beyond what
  Hasura can utilize, to ensure that database does not become part of
  the System Under Test (SUT).

* Why

Hasura's through-put (and latency) are partially determined by the
available compute resources.  It is worthwhile to obtain evidence for
how through-put (and potentially latency) relate to the available
compute resources.  This evidence can be used to model how well Hasura
uses additional compute resources that are made available, and can be
used to guide infrastructure, provisioning, and cost estimates for
Hasura. 

* How



* Steps

*** Local Testing

1. Clone this repository.
2. Install Docker and Docker Compose.
3. Install k6.
4. Install the DigitalOcean CLI.
5. Run the test script.

   #+begin_src shell
     export DIGITALOCEAN_TOKEN= # Paste in your DigitalOcean API token.
     export SSH_KEYID= # Paste in your DigitalOcean SSH Key ID.
     bash test.bash
   #+end_src
   
*** Remote Testing

1. Clone the battery repository.
2. Install the DigitalOcean CLI.
3. Run the test harness Make target with the test script repository URL.

   #+begin_src shell
     export DIGITALOCEAN_TOKEN= # Paste in your DigitalOcean API token.
     export SSH_KEYID= # Paste in your DigitalOcean SSH Key ID.
     export GIT_URL=https://github.com/dventimihasura/battery-test-6.git
     make up
   #+end_src
